### PR TITLE
Beta For Converting to Typescript

### PR DESCRIPTION
**Pull request by donavanbecker**

### CODE REVIEW

**Comment by SmolSoftBoi** [comment]
#69 I've added some additional fixes here. This should be a good base to go from and uses Homebridge's plugin template for consistency. Once this has been done, it would be a good idea to figure out how to move away from Homebridge's depreciated APIs.

**Comment by donavanbecker** [comment]
> #69 I've added some additional fixes here. This should be a good base to go from and uses Homebridge's plugin template for consistency. Once this has been done, it would be a good idea to figure out how to move away from Homebridge's depreciated APIs.

@EpicKris I am getting the following error when installing beta now that I have merged.

```
[7/13/2020, 4:48:47 PM] TypeError: node_arlo_1.Arlo is not a constructor
    at new ArloPlatform (/usr/local/lib/node_modules/homebridge-arlo/src/platform.ts:20:26)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
```

**Comment by SmolSoftBoi** [comment]
@donavanbecker Looks like an import wasn't included correctly, fixed in pull request #71

**Comment by donavanbecker** [comment]
now these

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ArloBaseStation'
    |     property 'parent' -> object with constructor 'Arlo'
    |     property 'devices' -> object with constructor 'Object'
    --- property 'A081987DA035D' closes the circle
    at Object.stringify (<anonymous>)
    at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:476:44)
    at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:277:14)
    at Server.saveCachedPlatformAccessoriesOnDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:320:24)
    at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:529:10)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
    at Arlo.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/src/platform.ts:170:18)
    at Arlo.emit (events.js:315:20)
    at Arlo.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:40:26)
```


```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ArloBaseStation'
    |     property 'parent' -> object with constructor 'Arlo'
    |     property 'devices' -> object with constructor 'Object'
    --- property 'A081987DA035D' closes the circle
    at Object.stringify (<anonymous>)
    at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:476:44)
    at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:277:14)
    at Server.saveCachedPlatformAccessoriesOnDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:320:24)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:607:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:64:12)
    at process.emit (events.js:315:20)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:495:21)
```

**Comment by EpicKris** [comment]
@donavanbecker Could you provide an example of your config?

**Comment by SmolSoftBoi** [comment]
@donavanbecker After a bit of digging, it looks like the `TypeError: Converting circular structure to JSON` error is when HomeBridge attempts to cache the accessory state (and more importantly, the context). The device context from `node-arlo` has a circular referencing structure.

An example to reproduce this issue outside of Homebridge would be to serialise a `node-arlo` device using `JSON.stringify`. I think this issue would be best resolved in `node-arlo` to allow those instances to be serialised correctly as this could possibly affect any future development using that dependency. We can use `serialize` and `deserialize` static functions.

**Comment by donavanbecker** [comment]
@EpicKris Do you wanna create a pull request to node-arlo?

**Comment by donavanbecker** [comment]
> Do you wanna create a pull request to node-arlo?

@EpicKris, looks like you already did. ha when building though, we are getting an [error](https://github.com/homebridge-plugins/homebridge-arlo/runs/878022592?check_suite_focus=true#step:4:1072).

Also do you want access to help maintain this repo?

**Comment by SmolSoftBoi** [comment]
> @EpicKris, looks like you already did. ha when building though, we are getting an [error](https://github.com/homebridge-plugins/homebridge-arlo/runs/878022592?check_suite_focus=true#step:4:1072).

I'll check this error tonight.

> Also do you want access to help maintain this repo?

That would be great.

**Comment by donavanbecker** [comment]
> That would be great.

you will have to delete your fork of homebridge-arlo and then I will transfer it over to you.

**Comment by donavanbecker** [comment]
@EpicKris looks like latest beta built correctly with latest changes to node-arlo. I will see if it works with my account. or if I still get these errors.

**Comment by donavanbecker** [comment]
@EpicKris still getting the following with the latest node-arlo.

```
[7/21/2020, 10:08:44 PM] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ArloBaseStation'
    |     property 'parent' -> object with constructor 'Arlo'
    |     property 'devices' -> object with constructor 'Object'
    --- property 'A081987DA035D' closes the circle
    at Object.stringify (<anonymous>)
    at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:476:44)
    at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:277:14)
    at Server.saveCachedPlatformAccessoriesOnDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:318:24)
    at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:527:10)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
    at Arlo.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/src/platform.ts:170:18)
    at Arlo.emit (events.js:315:20)
    at Arlo.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:40:26)
[7/21/2020, 10:08:44 PM] Got SIGTERM, shutting down Homebridge...
[7/21/2020, 10:08:44 PM] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ArloBaseStation'
    |     property 'parent' -> object with constructor 'Arlo'
    |     property 'devices' -> object with constructor 'Object'
    --- property 'A081987DA035D' closes the circle
    at Object.stringify (<anonymous>)
    at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:476:44)
    at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:277:14)
    at Server.saveCachedPlatformAccessoriesOnDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:318:24)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:605:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:64:12)
    at process.emit (events.js:315:20)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:495:21)
```

**Comment by SmolSoftBoi** [comment]
> @EpicKris still getting the following with the latest node-arlo.

I'm currently in the process of rewriting `node-arlo` which will include fully typed responses.

**Pull request closed without merging**
